spring.application.name=E_Commerce_Application

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#jpa and hibernate properties/configurations

#this will show the sql queries running internally in console
spring.jpa.show-sql=true
#for automatically update database after every change
spring.jpa.hibernate.ddl-auto=update
#it converts the java data types into database data type
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
spring.jpa.open-in-view=false
spring-boot.run.jvmArguments=-XX:+EnableDynamicAgentLoading

cloudinary.cloud_name=${CLOUDINARY.CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY.API_KEY}
cloudinary.api_secret=${CLOUDINARY.API_SECRET}

openrouter.api.key=${OPENROUTER.API.KEY}

//After placing the order on cash on deleviry To send a email to user ki your order placed successfully

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${SPRING.MAIL.USERNAME}
spring.mail.password=${SPRING.MAIL.PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}








